### PR TITLE
Implement cksum --raw

### LINKED ISSUE #5708: Implement `cksum --raw`
According to GNU:
```       
--raw  emit a raw binary digest, not hexadecimal
```
Tested in GNU with tests/cksum/cksum-raw.sh 
Source:
https://github.com/uutils/coreutils/blob/main/src/uu/cksum/src/cksum.rs

### PR DESCRIPTION
**Pull request by D9nni**
I will try to add --raw option to cksum, in order to fix https://github.com/uutils/coreutils/issues/5708

### CODE REVIEW

**Comment by alexandruradovici** [comment]
Please write a detailed message in the pull request description.

**Comment by alexandruradovici** [comment]
Send this to upstream and put a link to the pull request here.

**Comment by alexandruradovici** [comment]
Please rebase your branch before sending this to upstream.

**Comment by D9nni** [comment]
https://github.com/uutils/coreutils/pull/5803

**Comment by D9nni** [comment]
> [uutils#5803](https://github.com/uutils/coreutils/pull/5803)

The pull request sent to upstream was merged, after more improvements made on this code.

**Pull request closed without merging**
